# Generated by Django 2.2 on 2019-04-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_auto_20190403_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='animal',
            new_name='owner',
        ),
    ]
